<?php

namespace Database\Seeders;

use App\Models\CourseChapterLesson;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LessonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $lessons =
            [
                [
                    'id' => 5,
                    'title' => 'Installing Your Toolkit',
                    'slug' => 'installing-your-toolkit',
                    'description' => 'Setting up Anaconda or Miniconda
Creating virtual environments
Managing packages with pip and conda',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 9,
                    'file_path' => 'https://www.youtube.com/watch?v=rIfdg_Ot-LI&ab_channel=Fireship',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 10,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 1,
                    'is_preview' => 1,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:01:11',
                    'updated_at' => '2025-05-11 08:01:11',
                ],
                [
                    'id' => 6,
                    'title' => 'Python Basics Refresher',
                    'slug' => 'python-basics-refresher',
                    'description' => 'Variables, data types, and basic operations
Control flow: if statements, loops
Writing and calling functions',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 9,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 8,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 2,
                    'is_preview' => 1,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:02:23',
                    'updated_at' => '2025-05-11 08:02:23',
                ],
                [
                    'id' => 7,
                    'title' => 'Working with Data Structures',
                    'slug' => 'working-with-data-structures',
                    'description' => 'Lists, tuples, sets, dictionaries
List/dict comprehensions
When to use each structure',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 9,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 17,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 3,
                    'is_preview' => 1,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:03:11',
                    'updated_at' => '2025-05-11 08:03:11',
                ],
                [
                    'id' => 8,
                    'title' => 'Modules and Packages',
                    'slug' => 'modules-and-packages',
                    'description' => 'Standard library modules you need
Import syntax and best practices
Creating your own modules',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 9,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 25,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 4,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:03:38',
                    'updated_at' => '2025-05-11 08:03:38',
                ],
                [
                    'id' => 9,
                    'title' => 'Reading CSVs with pandas',
                    'slug' => 'reading-csvs-with-pandas',
                    'description' => 'Using pd.read_csv() options
Handling delimiters, encodings, large files',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 10,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 14,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 1,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:11:07',
                    'updated_at' => '2025-05-11 08:11:07',
                ],
                [
                    'id' => 10,
                    'title' => 'Excel, JSON & SQL Sources',
                    'slug' => 'excel-json-sql-sources',
                    'description' => 'pd.read_excel(), pd.read_json()
Connecting to a SQLite/MySQL database',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 10,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 5,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 2,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:11:32',
                    'updated_at' => '2025-05-11 08:11:32',
                ],
                [
                    'id' => 11,
                    'title' => 'Web Scraping for Data',
                    'slug' => 'web-scraping-for-data',
                    'description' => 'Using requests & BeautifulSoup
Parsing HTML tables',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 10,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 20,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 3,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:11:56',
                    'updated_at' => '2025-05-11 08:11:56',
                ],
                [
                    'id' => 12,
                    'title' => 'APIs and JSON into DataFrames',
                    'slug' => 'apis-and-json-into-dataframes',
                    'description' => 'Consuming RESTful APIs
Normalizing nested JSON into tabular form',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 10,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 12,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 4,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:12:25',
                    'updated_at' => '2025-05-11 08:12:25',
                ],
                [
                    'title' => 'Matplotlib Fundamentals',
                    'slug' => 'matplotlib-fundamentals',
                    'description' => 'Creating line, bar, and scatter plots. Customizing axes, titles, and legends.',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 13,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 20,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 1,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:13:00',
                    'updated_at' => '2025-05-11 08:13:00',
                ],
                [
                    'title' => 'Visualizing DataFrames Directly',
                    'slug' => 'visualizing-dataframes-directly',
                    'description' => 'Pandas’ built-in .plot() interface. Quick plots vs. full customization.',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 14,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 18,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 2,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:13:30',
                    'updated_at' => '2025-05-11 08:13:30',
                ],
                [
                    'title' => 'Advanced Plots: Histograms, Boxplots & KDE',
                    'slug' => 'advanced-plots-histograms-boxplots-kde',
                    'description' => 'Distribution visualizations. Comparing groups side-by-side.',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 14,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 25,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 3,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:14:00',
                    'updated_at' => '2025-05-11 08:14:00',
                ],
                [
                    'title' => 'Time Series Plotting',
                    'slug' => 'time-series-plotting',
                    'description' => 'Plotting date-indexed data. Rolling statistics and overlays.',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 14,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 22,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 4,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:14:30',
                    'updated_at' => '2025-05-11 08:14:30',
                ],
                [
                    'title' => 'Seaborn Overview (Optional)',
                    'slug' => 'seaborn-overview-optional',
                    'description' => 'Integrating Seaborn for attractive defaults. Pairplots and jointplots.',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 14,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 5,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:15:00',
                    'updated_at' => '2025-05-11 08:15:00',
                ],
                [
                    'title' => 'ndarray Basics',
                    'slug' => 'ndarray-basics',
                    'description' => 'Creating arrays, indexing, slicing',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 15,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 1,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:15:30',
                    'updated_at' => '2025-05-11 08:15:30',
                ],
                [
                    'title' => 'Broadcasting rules',
                    'slug' => 'broadcasting-rules',
                    'description' => '',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 15,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 2,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:16:00',
                    'updated_at' => '2025-05-11 08:16:00',
                ],
                [
                    'title' => 'Vectorized Operations',
                    'slug' => 'vectorized-operations',
                    'description' => 'Arithmetic, comparison, boolean masking',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 15,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 3,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:16:30',
                    'updated_at' => '2025-05-11 08:16:30',
                ],
                [
                    'title' => 'Speed benefits over pure Python loops',
                    'slug' => 'speed-benefits-over-pure-python-loops',
                    'description' => '',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 15,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 4,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:17:00',
                    'updated_at' => '2025-05-11 08:17:00',
                ],
                [
                    'title' => 'Linear Algebra & Statistics',
                    'slug' => 'linear-algebra-statistics',
                    'description' => 'Dot products, matrix multiplication',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 15,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 5,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:17:30',
                    'updated_at' => '2025-05-11 08:17:30',
                ],
                [
                    'title' => 'Mean, median, standard deviation',
                    'slug' => 'mean-median-standard-deviation',
                    'description' => '',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 15,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 6,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:18:00',
                    'updated_at' => '2025-05-11 08:18:00',
                ],
                [
                    'title' => 'Integrating NumPy with pandas',
                    'slug' => 'integrating-numpy-with-pandas',
                    'description' => 'Converting between DataFrames and ndarrays',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 15,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 7,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:18:30',
                    'updated_at' => '2025-05-11 08:18:30',
                ],
                [
                    'title' => 'Probability Distributions',
                    'slug' => 'probability-distributions',
                    'description' => 'Normal, binomial, Poisson in scipy.stats',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 16,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 1,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:19:00',
                    'updated_at' => '2025-05-11 08:19:00',
                ],
                [
                    'title' => 'Sampling and Random Variates',
                    'slug' => 'sampling-and-random-variates',
                    'description' => '',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 16,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 2,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:19:30',
                    'updated_at' => '2025-05-11 08:19:30',
                ],
                [
                    'title' => 'Hypothesis Testing',
                    'slug' => 'hypothesis-testing',
                    'description' => 'T-tests, chi-square tests',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 16,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 3,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:20:00',
                    'updated_at' => '2025-05-11 08:20:00',
                ],
                [
                    'title' => 'Interpreting p-values',
                    'slug' => 'interpreting-p-values',
                    'description' => '',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 16,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 4,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:20:30',
                    'updated_at' => '2025-05-11 08:20:30',
                ],
                [
                    'title' => 'Regression Basics',
                    'slug' => 'regression-basics',
                    'description' => 'Simple linear regression with statsmodels',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 16,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 5,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:21:00',
                    'updated_at' => '2025-05-11 08:21:00',
                ],
                [
                    'title' => 'Assessing Model Fit',
                    'slug' => 'assessing-model-fit',
                    'description' => 'R², residuals',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 16,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 6,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:21:30',
                    'updated_at' => '2025-05-11 08:21:30',
                ],
                [
                    'title' => 'Putting It All Together',
                    'slug' => 'putting-it-all-together',
                    'description' => 'Small case study: A/B test analysis',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 16,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 7,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:22:00',
                    'updated_at' => '2025-05-11 08:22:00',
                ],
                [
                    'title' => 'Final Capstone Project Project Proposal & Dataset Selection',
                    'slug' => 'final-capstone-project-project-proposal-dataset-selection',
                    'description' => 'Defining a clear question or hypothesis, Sourcing and justifying chosen data',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 17,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 1,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:22:30',
                    'updated_at' => '2025-05-11 08:22:30',
                ],
                [
                    'title' => 'End-to-End Pipeline',
                    'slug' => 'end-to-end-pipeline',
                    'description' => 'Data ingestion → cleaning → EDA → visualization',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 17,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 2,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:23:00',
                    'updated_at' => '2025-05-11 08:23:00',
                ],
                [
                    'title' => 'Statistical Insights & Modeling',
                    'slug' => 'statistical-insights-modeling',
                    'description' => 'Applying simple models or statistical tests, Highlighting key findings',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 17,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 3,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:23:30',
                    'updated_at' => '2025-05-11 08:23:30',
                ],
                [
                    'title' => 'Reporting & Presentation',
                    'slug' => 'reporting-presentation',
                    'description' => 'Creating a Jupyter-based report, Best practices for clear, reproducible narratives',
                    'instructor_id' => 2,
                    'course_id' => 6,
                    'chapter_id' => 17,
                    'file_path' => 'https://youtube.com',
                    'storage' => 'youtube',
                    'volume' => null,
                    'duration' => 30,
                    'file_type' => 'video',
                    'downloadable' => 0,
                    'order' => 4,
                    'is_preview' => 0,
                    'status' => 1,
                    'lesson_type' => 'lesson',
                    'created_at' => '2025-05-11 08:24:00',
                    'updated_at' => '2025-05-11 08:24:00',
                ]
            ];

        foreach ($lessons as $lesson) {
            $existingLesson = CourseChapterLesson::firstOrNew(['chapter_id' => $lesson['chapter_id'], 'title' => $lesson['title']]);

            if ($existingLesson->exists) {
                // If the lesson already exists, update its data
                $existingLesson->update($lesson);
            } else {
                // If the lesson does not exist, create a new one
                CourseChapterLesson::create($lesson);
            }
        }
    }
}
